"""
src/preprocessing.py
=====================
Data loading, cleaning, and train/validation/test splitting.

Key responsibilities
--------------------
1. Load raw CSV attendance data.
2. Validate required columns.
3. Clean / impute missing values.
4. Parse dates and time components.
5. Split into train / validation / test sets WITHOUT leaking ground-truth labels
   into the feature matrix used for unsupervised model training.

Data-leakage prevention
------------------------
The column ``is_anomaly`` is the ground-truth label.
It is separated from the feature matrix BEFORE any ML step.
The unsupervised models see ONLY the feature matrix X.
The labels y are stored separately for evaluation purposes only.
"""

from __future__ import annotations

import logging
from typing import Tuple

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

logger = logging.getLogger(__name__)

# ─────────────────────────────────────────────
# Required raw columns (generated by generate_dataset.py)
# ─────────────────────────────────────────────
REQUIRED_COLUMNS = [
    "student_id", "date", "day_of_week", "class_id",
    "attendance_status", "attendance_time", "hour", "minute",
    "location_id", "ip_address", "device_id",
    "previous_attendance_gap", "weekly_attendance_rate",
    "monthly_attendance_rate", "total_classes", "classes_attended",
    "late_count", "absence_count", "proxy_risk_indicator",
    "historical_deviation", "is_anomaly",
]

# Columns that must be numeric (checked after loading)
NUMERIC_COLUMNS = [
    "day_of_week", "class_id", "hour", "minute", "location_id",
    "previous_attendance_gap", "weekly_attendance_rate",
    "monthly_attendance_rate", "total_classes", "classes_attended",
    "late_count", "absence_count", "proxy_risk_indicator",
    "historical_deviation",
]


def load_data(filepath: str) -> pd.DataFrame:
    """
    Load a CSV attendance file and perform basic validation.

    Parameters
    ----------
    filepath : str
        Path to the CSV file.

    Returns
    -------
    pd.DataFrame
        Raw DataFrame with validated columns.

    Raises
    ------
    FileNotFoundError
        If the CSV file does not exist.
    ValueError
        If required columns are missing or the file is empty.
    """
    import os
    if not os.path.exists(filepath):
        raise FileNotFoundError(f"Dataset not found: {filepath}")

    df = pd.read_csv(filepath)

    if df.empty:
        raise ValueError("The loaded dataset is empty.")

    # ── Column validation ────────────────────────────────────────────────
    missing_cols = [c for c in REQUIRED_COLUMNS if c not in df.columns]
    if missing_cols:
        raise ValueError(
            f"Missing required columns: {missing_cols}\n"
            f"Available columns: {list(df.columns)}"
        )

    logger.info("Loaded %d records from '%s'.", len(df), filepath)
    return df


def clean_data(df: pd.DataFrame) -> pd.DataFrame:
    """
    Clean and sanitise the attendance DataFrame.

    Steps
    -----
    1. Drop duplicated rows.
    2. Parse the ``date`` column to datetime.
    3. Coerce numeric columns; replace NaN with column medians.
    4. Clip rates to [0, 1].
    5. Ensure ``hour`` is within [0, 23] and ``minute`` within [0, 59].

    Parameters
    ----------
    df : pd.DataFrame
        Raw attendance data.

    Returns
    -------
    pd.DataFrame
        Cleaned DataFrame.
    """
    df = df.copy()

    # ── Remove exact duplicates
    before = len(df)
    df = df.drop_duplicates()
    logger.info("Dropped %d duplicate rows.", before - len(df))

    # ── Parse date ──────────────────────────────────────────────────────
    df["date"] = pd.to_datetime(df["date"], errors="coerce")
    invalid_dates = df["date"].isna().sum()
    if invalid_dates > 0:
        logger.warning("Dropped %d rows with unparseable dates.", invalid_dates)
        df = df.dropna(subset=["date"])

    # ── Coerce numeric columns ───────────────────────────────────────────
    for col in NUMERIC_COLUMNS:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")
            if df[col].isna().any():
                median_val = df[col].median()
                logger.warning(
                    "Column '%s' has NaN values; filling with median %.4f.", col, median_val
                )
                df[col] = df[col].fillna(median_val)

    # ── Clip rates to valid range [0, 1] ────────────────────────────────
    for rate_col in ["weekly_attendance_rate", "monthly_attendance_rate"]:
        if rate_col in df.columns:
            df[rate_col] = df[rate_col].clip(0.0, 1.0)

    # ── Sanity-check time components ─────────────────────────────────────
    df["hour"]   = df["hour"].clip(0, 23).astype(int)
    df["minute"] = df["minute"].clip(0, 59).astype(int)

    logger.info("Cleaned dataset has %d records.", len(df))
    return df


def split_data(
    df: pd.DataFrame,
    train_ratio:  float = 0.60,
    val_ratio:    float = 0.20,
    test_ratio:   float = 0.20,
    random_state: int   = 42,
) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame,
           pd.Series,   pd.Series,   pd.Series]:
    """
    Split data into train / validation / test sets.

    Important
    ---------
    The split is performed on the FULL dataframe (including anomalies) so
    that each split reflects the natural anomaly distribution.
    The ground-truth label (``is_anomaly``) is separated AFTER splitting
    and is NEVER passed to the unsupervised training step.

    Parameters
    ----------
    df           : pd.DataFrame  – cleaned attendance data
    train_ratio  : float         – fraction for training (default 0.60)
    val_ratio    : float         – fraction for validation (default 0.20)
    test_ratio   : float         – fraction for test (default 0.20)
    random_state : int           – reproducibility seed

    Returns
    -------
    X_train, X_val, X_test : pd.DataFrame – feature matrices
    y_train, y_val, y_test : pd.Series    – ground-truth labels (0/1)
    """
    assert abs(train_ratio + val_ratio + test_ratio - 1.0) < 1e-6, \
        "Ratios must sum to 1.0"

    # ── Separate labels FIRST ────────────────────────────────────────────
    # The label column is popped so that it never accidentally ends up
    # inside the feature matrix passed to the anomaly detectors.
    labels = df["is_anomaly"].astype(int)
    features = df.drop(columns=["is_anomaly", "anomaly_type"], errors="ignore")

    # ── Train / temp split ───────────────────────────────────────────────
    X_train, X_temp, y_train, y_temp = train_test_split(
        features, labels,
        test_size=(1.0 - train_ratio),
        random_state=random_state,
        stratify=labels,     # preserve anomaly ratio in each split
    )

    # ── Validation / test split ──────────────────────────────────────────
    relative_val = val_ratio / (val_ratio + test_ratio)
    X_val, X_test, y_val, y_test = train_test_split(
        X_temp, y_temp,
        test_size=(1.0 - relative_val),
        random_state=random_state,
        stratify=y_temp,
    )

    logger.info(
        "Split sizes → train: %d | val: %d | test: %d",
        len(X_train), len(X_val), len(X_test)
    )
    logger.info(
        "Anomaly counts → train: %d | val: %d | test: %d",
        y_train.sum(), y_val.sum(), y_test.sum()
    )

    return X_train, X_val, X_test, y_train, y_val, y_test
